### ISSUE TITLE
[Feature request] More granular templating options!

### ISSUE THREAD

**Issue by lukthony** [ebullient/fc5-convert-cli#13]
Currently, templating requires adhering to a certain output format. For example, `{resource.scores}` outputs `STAT (BONUS) | STAT (BONUS) | STAT (BONUS) | STAT (BONUS) | STAT (BONUS) | STAT (BONUS)`. This poses an issue if, for example, the user wants to make a template that adheres to the [Obsidian statblock plugin](https://github.com/valentine195/obsidian-5e-statblocks)'s syntax.

In order to be able to match said statblock plugin(and just to gain fully granular control over the template in general), there'd have to be ways to access:
- Individual stats (sans bonus)
- Subtype
- Hit dice (separated from HP)
- Saves
- Damage vulnerabilities, damage resistances, and damage/condition immunities
- Senses
- Languages

**Comment by ebullient** [comment]
Almost there! Just sorting out YAML

**Comment by ebullient** [comment]
Ok! What I've done is a bit of both. There are lots more fiddly bits for monsters (that I would have to write docs for).. but I knew what you were really trying to do, so I made a shortcut: 

````
---
cssclass: 5e-monster
aliases: ['{resource.name}']
tags:
{#for tag in resource.tags}
- {tag}
{/for}
---
# {resource.name}
{#if resource.description }
{resource.description}
{/if}
```statblock
{resource.5eStatblockYaml}
```

## Environment

{resource.environment}
````

This will still pull in the wordy description and/or environment strings (and the tags, etc.), but uses a yaml library to encode the guts of the 5e statblock because going through a template to do that was going to give everyone headaches. ;)

Let me know if things are missing!
